"""initial schema

Revision ID: 5736d245a352
Revises: 
Create Date: 2026-06-23 14:15:03.206094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5736d245a352'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_type', sa.Enum('quiz', 'exam', name='assessmenttype'), nullable=False),
    sa.Column('quiz_password', sa.String(length=255), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_course_id'), 'assessments', ['course_id'], unique=False)
    op.create_index(op.f('ix_assessments_lesson_id'), 'assessments', ['lesson_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'true_false', 'short_answer', name='questiontype'), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_assessment_id', 'questions', ['assessment_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'graded', name='submissionstatus'), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_assessment_id', 'submissions', ['assessment_id'], unique=False)
    op.create_index('ix_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('ix_submissions_student_id', 'submissions', ['student_id'], unique=False)
    op.create_table('violation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.Enum('tab_switch', 'copy_paste', 'multiple_faces', 'no_face', 'other', name='violationtype'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_violation_logs_student_id', 'violation_logs', ['student_id'], unique=False)
    op.create_index(op.f('ix_violation_logs_submission_id'), 'violation_logs', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violation_logs_submission_id'), table_name='violation_logs')
    op.drop_index('ix_violation_logs_student_id', table_name='violation_logs')
    op.drop_table('violation_logs')
    op.drop_index('ix_submissions_student_id', table_name='submissions')
    op.drop_index('ix_submissions_status', table_name='submissions')
    op.drop_index('ix_submissions_assessment_id', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_questions_assessment_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_assessments_lesson_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_course_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
