"""initial schema

Revision ID: 208e3354fe81
Revises: 
Create Date: 2026-06-23 14:14:58.885304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208e3354fe81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('receipt_url', sa.String(length=512), nullable=False),
    sa.Column('receipt_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='receiptstatus'), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_receipts_payment_id', 'payment_receipts', ['payment_id'], unique=False)
    op.create_index('ix_payment_receipts_student_id', 'payment_receipts', ['student_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('MANUAL', 'PAYHERE', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reference_no', sa.String(length=255), nullable=True),
    sa.Column('payhere_order_id', sa.String(length=255), nullable=True),
    sa.Column('due_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payhere_order_id')
    )
    op.create_index('ix_payments_course_id', 'payments', ['course_id'], unique=False)
    op.create_index(op.f('ix_payments_enrollment_id'), 'payments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_payments_reference_no'), 'payments', ['reference_no'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index(op.f('ix_payments_reference_no'), table_name='payments')
    op.drop_index(op.f('ix_payments_enrollment_id'), table_name='payments')
    op.drop_index('ix_payments_course_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_payment_receipts_student_id', table_name='payment_receipts')
    op.drop_index('ix_payment_receipts_payment_id', table_name='payment_receipts')
    op.drop_table('payment_receipts')
    # ### end Alembic commands ###
