"""initial schema

Revision ID: 2983359d1d84
Revises:
Create Date: 2026-06-23 14:14:51.625426

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2983359d1d84"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
