"""initial schema

Revision ID: c4a18f703187
Revises:
Create Date: 2026-06-23 14:15:07.033600

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4a18f703187"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("certificate_url", sa.String(length=512), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "course_id", name="uq_certificate_student_course"
        ),
    )
    op.create_index(
        "ix_certificates_course_id", "certificates", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_certificates_student_id"), "certificates", ["student_id"], unique=False
    )
    op.create_table(
        "course_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("in_progress", "completed", name="courseprogressstatus"),
            nullable=False,
        ),
        sa.Column("completed_lessons_count", sa.Integer(), nullable=False),
        sa.Column("total_lessons_count", sa.Integer(), nullable=False),
        sa.Column(
            "completion_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "course_id", name="uq_course_progress_student_course"
        ),
    )
    op.create_index(
        "ix_course_progress_course_id", "course_progress", ["course_id"], unique=False
    )
    op.create_index(
        "ix_course_progress_student_id", "course_progress", ["student_id"], unique=False
    )
    op.create_table(
        "leaderboard_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("streak_days", sa.Integer(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "course_id", name="uq_leaderboard_student_course"
        ),
    )
    op.create_index(
        op.f("ix_leaderboard_entries_course_id"),
        "leaderboard_entries",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        "ix_leaderboard_entries_points", "leaderboard_entries", ["points"], unique=False
    )
    op.create_index(
        op.f("ix_leaderboard_entries_student_id"),
        "leaderboard_entries",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "lesson_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("watch_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("last_position_seconds", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "lesson_id", name="uq_lesson_progress_student_lesson"
        ),
    )
    op.create_index(
        op.f("ix_lesson_progress_course_id"),
        "lesson_progress",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_progress_lesson_id"),
        "lesson_progress",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_progress_student_id"),
        "lesson_progress",
        ["student_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lesson_progress_student_id"), table_name="lesson_progress")
    op.drop_index(op.f("ix_lesson_progress_lesson_id"), table_name="lesson_progress")
    op.drop_index(op.f("ix_lesson_progress_course_id"), table_name="lesson_progress")
    op.drop_table("lesson_progress")
    op.drop_index(
        op.f("ix_leaderboard_entries_student_id"), table_name="leaderboard_entries"
    )
    op.drop_index("ix_leaderboard_entries_points", table_name="leaderboard_entries")
    op.drop_index(
        op.f("ix_leaderboard_entries_course_id"), table_name="leaderboard_entries"
    )
    op.drop_table("leaderboard_entries")
    op.drop_index("ix_course_progress_student_id", table_name="course_progress")
    op.drop_index("ix_course_progress_course_id", table_name="course_progress")
    op.drop_table("course_progress")
    op.drop_index(op.f("ix_certificates_student_id"), table_name="certificates")
    op.drop_index("ix_certificates_course_id", table_name="certificates")
    op.drop_table("certificates")
    # ### end Alembic commands ###
