"""initial schema

Revision ID: e51ca3e470a6
Revises:
Create Date: 2026-06-23 14:15:09.376711

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e51ca3e470a6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "enrollment_confirmed",
                "payment_received",
                "payment_rejected",
                "assessment_graded",
                "certificate_issued",
                "course_published",
                "general",
                name="notificationevent",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("in_app", "email", "push", name="notificationchannel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="notificationstatus"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_logs_is_read", "notification_logs", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_notification_logs_recipient_id"),
        "notification_logs",
        ["recipient_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_logs_status", "notification_logs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_logs_status", table_name="notification_logs")
    op.drop_index(
        op.f("ix_notification_logs_recipient_id"), table_name="notification_logs"
    )
    op.drop_index("ix_notification_logs_is_read", table_name="notification_logs")
    op.drop_table("notification_logs")
    # ### end Alembic commands ###
